apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv

spec:
  # NULL means static
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.43.235
    path: "/mydata"
