apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  storageClassName: ""

  capacity:
    storage: 1Gi
  
  accessModes:
    - ReadWriteOnce

  # hostPath is a kyword for using host machine local storage
  hostPath:
    path: "/mydata" 
