apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc

spec:
  # set the access modes
  accessModes:
    - ReadWriteOnce

  # what I wanna do
  resources:
    requests:    
      storage: 1Gi
