apiVersion: v1
kind: ReplicationController
metadata:
  name: "myrc1"

spec:
  replicas: 10
  selector:
    app: web
  template:
    metadata:
      name: 'mypod'
      labels:
        app: web

    spec:
      containers:
        - name: myc1
          image: vimal13/apache-webserver-php

